// import Next
import Head from "next/head";

// import component
import Header from "@/components/Header";

// import style
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sea Adventures</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <Header />
      <main>Hello there!</main>
    </>
  );
}
